name: Lint

on:
  - push
  - pull_request
branch:
  - main
jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm install --global awesome-lint
      - run: awesome-lint README.md
  awesome-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install awesome_bot
      - run: awesome_bot README.md --allow 302,307 --allow-ssl --allow-dupe --white-list "linode.com"